### PR TITLE
Build naughty list middleware

### LINKED ISSUE #565: Naughty List
Repcoin needs middleware that will not allow users to add words with malicious content

### PR DESCRIPTION
**Pull request by ritmatter**
Fixes #565

Not a comprehensive list or complete strategy but a good start

### CODE REVIEW

**Comment by krazemon** [comment]
Maybe we shouldn't have the naughty list on Github?

**Comment by ritmatter** [comment]
so the reason its tough to keep the naughtylist off github is because you cant push things that are ignored from github to heroku

Matt Ritter [2:16 PM]
i did some digging and its almost impossible to put files on there through scp or anything like that

Matt Ritter [2:17 PM]
this is the main reason why i took out the whitelist from acl, since i couldnt figure out how to get it onto heroku without exposing it to git

Matt Ritter [2:17 PM]
another solution would be to have a private repo that integrates with heroku and a public repo for portfolio/resume purposes

Matt Ritter [2:17 PM]
that being said i dont think its a huge deal if some naughty words are on github

**Comment by ritmatter** [comment]
Is this LGTM?

**Comment by krazemon** [comment]
Yeah

**Comment by harquail** [comment]
here are some more dirty words, if you want them: https://github.com/harquail/wordlists/blob/master/WordListsParser/WordListsParser/comparisonLists/offensiveWords.txt

**Comment by krazemon** [comment]
Thanks!

**Pull request merged**
